// Agent Prompts 模块导出

export {
  ORCHESTRATOR_IDENTITY,
  ORCHESTRATOR_RESPONSIBILITIES,
  ORCHESTRATOR_DELEGATION_RULES,
  ORCHESTRATOR_TOOL_CONTRACT,
  ORCHESTRATOR_SYSTEM_PROMPT,
} from "./orchestrator-prompts";

export {
  WRITER_FORMAT_RULES,
  WRITER_ANTIAI_RULES,
  WRITER_PACING_RULES,
  WRITER_GOLDEN_OPENING,
  WRITER_PRE_WRITE_CHECK,
  WRITER_OUTPUT_FORMAT,
  WRITER_SYSTEM_PROMPT,
} from "./writer-prompts";

export {
  AUDITOR_IDENTITY,
  AUDITOR_CHARACTER_MEMORY,
  AUDITOR_MATERIAL_CONTINUITY,
  AUDITOR_FORESHADOWING,
  AUDITOR_OUTLINE_DEVIATION,
  AUDITOR_NARRATIVE_RHYTHM,
  AUDITOR_AI_TRACES,
  AUDITOR_GOLDEN_OPENING,
  AUDITOR_37_DIMENSIONS,
  AUDITOR_OUTPUT_FORMAT,
  AUDITOR_SYSTEM_PROMPT,
} from "./auditor-prompts";

export {
  CODE_REVIEWER_IDENTITY,
  CODE_REVIEWER_FINDER_ANGLES,
  CODE_REVIEWER_VERIFICATION_RULES,
  CODE_REVIEWER_OUTPUT_FORMAT,
  CODE_REVIEWER_SYSTEM_PROMPT,
} from "./code-reviewer-prompts";

export {
  DEEP_RESEARCHER_IDENTITY,
  DEEP_RESEARCHER_WORKFLOW,
  DEEP_RESEARCHER_VERIFICATION_RULES,
  DEEP_RESEARCHER_OUTPUT_FORMAT,
  DEEP_RESEARCHER_SYSTEM_PROMPT,
} from "./deep-researcher-prompts";